if we use then and catch block await not used because await also promise returning method

in console  go to settings  selected contexts only tick and untick do it 

id doesnt exit example in show route

next error validation error
